dist: xenial
language: cpp

addons:
  apt:
    packages:
      - ninja-build

matrix:
  include:
    - compiler: gcc
    - compiler: clang
      env:
        - CXXFLAGS="-stdlib=libc++"
        - LINKER_FLAGS="-stdlib=libc++"

script: ./scripts/build -c auto

