dist: xenial
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - ninja-build

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - libstdc++-7-dev


script: ./scripts/build -c auto

